spring:
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:top


top-application:
  spotify:
    url: https://api.spotify.com/v1/
    token-url: https://accounts.spotify.com/api/token
    client-id: e0feab84d9d94934916dbc91ed85425c
    client-secret: fa8ea27fbe4c42adb624566b34684ba9

caching:
  specs:
    albumCache:
      timeout: 7
      max: 200
    artistCache:
      timeout: 30
      max: 200

management:
  endpoints:
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always

